# Generated by Django 5.0.6 on 2024-05-28 20:07

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('author', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/images')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='articles.article')),
            ],
            options={
                'unique_together': {('article', 'language')},
            },
        ),
    ]
