# Generated by Django 5.0.6 on 2024-05-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_el',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_es',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_el',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_fr',
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
