# Generated by Django 5.0.6 on 2024-05-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_content_el_remove_article_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletranslation',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
