# Generated by Django 5.0.6 on 2024-06-01 07:38

"""
Initial migration for the geography app.
"""

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration class for initializing the geography app models.
    """

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='GeographicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Geographic Category',
                'verbose_name_plural': 'Geographic Categories',
            },
        ),
        migrations.CreateModel(
            name='GeographicContinent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Geographic Continent',
                'verbose_name_plural': 'Geographic Continents',
            },
        ),
        migrations.CreateModel(
            name='GeographicPlanet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mass', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('radius', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Geographic Planet',
                'verbose_name_plural': 'Geographic Planets',
            },
        ),
        migrations.CreateModel(
            name='GeographicCountry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('iso_alpha2', models.CharField(blank=True, max_length=2, unique=True)),
                ('iso_alpha3', models.CharField(blank=True, max_length=3, unique=True)),
                ('iso_numeric', models.IntegerField(blank=True, null=True, unique=True)),
                ('area', models.FloatField(null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('official_languages', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fetch_forecasts', models.BooleanField(default=False)),
                ('continent', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='countries',
                    to='geography.geographiccontinent'
                )),
            ],
            options={
                'verbose_name': 'Geographic Country',
                'verbose_name_plural': 'Geographic Countries',
            },
        ),
        migrations.CreateModel(
            name='GeographicCountryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField()),
                ('country', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='details',
                    to='geography.geographiccountry'
                )),
            ],
        ),
        migrations.CreateModel(
            name='GeographicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level_order', models.IntegerField()),
                ('country', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='levels',
                    to='geography.geographiccountry'
                )),
            ],
            options={
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='GeographicDivision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('country', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='admin_divisions',
                    to='geography.geographiccountry'
                )),
                ('parent', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='subdivisions',
                    to='geography.geographicdivision'
                )),
                ('level', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='divisions',
                    to='geography.geographiclevel'
                )),
            ],
            options={
                'verbose_name': 'Geographic Division',
                'verbose_name_plural': 'Geographic Divisions',
            },
        ),
        migrations.CreateModel(
            name='GeographicPlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(
                    blank=True, geography=True, null=True, srid=4326
                )),
                ('admin_division', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='places',
                    to='geography.geographicdivision'
                )),
                ('category', models.ForeignKey(
                    default=1, on_delete=django.db.models.deletion.SET_DEFAULT,
                    to='geography.geographiccategory'
                )),
            ],
            options={
                'verbose_name': 'Geographic Place',
                'verbose_name_plural': 'Geographic Places',
            },
        ),
    ]
