# Generated by Django 5.0.6 on 2024-05-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_assigned_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='custom_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
