# Generated by Django 5.0.6 on 2024-05-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Administrative Configuration',
                'verbose_name_plural': 'Administrative Configurations',
            },
        ),
        migrations.AlterModelOptions(
            name='admindivisioninstance',
            options={'verbose_name': 'Administrative Division Instance', 'verbose_name_plural': 'Administrative Division Instances'},
        ),
    ]
