# Generated by Django 5.0.6 on 2024-05-27 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_alter_place_admin_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='admin_division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='geography.admindivisioninstance'),
            preserve_default=False,
        ),
    ]
