# Generated by Django 5.0.6 on 2024-05-20 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_administrativeconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='place',
            name='admin_division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='geography.admindivisioninstance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='place',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='place',
            name='location',
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
    ]
