# Generated by Django 5.0.6 on 2024-05-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_alter_place_unique_together_place_admin_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level_order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['level_order'],
            },
        ),
    ]
