# Generated by Django 5.0.6 on 2024-05-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0004_instance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instance',
            options={},
        ),
        migrations.RemoveField(
            model_name='instance',
            name='level_order',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='name',
        ),
        migrations.AddField(
            model_name='instance',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instance',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
