# Generated by Django 5.0.6 on 2024-05-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0006_alter_admindivisioninstance_id_alter_continent_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instance',
        ),
    ]
