# Generated by Django 5.0.6 on 2024-05-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0007_delete_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='admin_division',
        ),
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('point_of_interest', 'Point of Interest')], default='point_of_interest', max_length=50),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
