# Generated by Django 5.0.6 on 2024-05-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0009_category_alter_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
