# Generated by Django 5.0.6 on 2024-05-20 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0010_place_height'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={},
        ),
        migrations.AddField(
            model_name='level',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='geography.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='admin_division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='geography.admindivisioninstance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='level',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('name', 'country')},
        ),
    ]
