# Generated by Django 5.0.6 on 2024-05-20 20:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0011_alter_level_options_level_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
