# Generated by Django 5.0.6 on 2024-05-15 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0002_counter_place_custom_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GFSForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_data', models.JSONField()),
                ('timestamp', models.DateTimeField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.place')),
            ],
        ),
    ]
