# Generated by Django 5.0.6 on 2024-05-20 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfsforecast',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_gfsforecasts', to='geography.place'),
        ),
    ]
