# Generated by Django 5.0.6 on 2024-06-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfsforecast',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gfsforecast',
            name='hour',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='gfsforecast',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gfsforecast',
            name='utc_cycle_time',
            field=models.DateTimeField(),
        ),
    ]
