# Generated by Django 5.0.6 on 2024-06-08 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GFSParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('level_layer', models.CharField(max_length=255)),
                ('parameter', models.CharField(max_length=255)),
                ('forecast_valid', models.CharField(default='N/A', max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('number', 'level_layer', 'parameter')},
            },
        ),
    ]
