# Generated by Django 5.0.6 on 2024-06-08 22:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_gfsforecast_date_alter_gfsforecast_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfsforecast',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
