# Generated by Django 5.0.6 on 2024-06-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_gfsforecast_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfsforecast',
            name='utc_cycle_time',
            field=models.CharField(choices=[('00', '00'), ('06', '06'), ('12', '12'), ('18', '18')], max_length=2),
        ),
    ]
