# Generated by Django 5.0.6 on 2024-05-20 14:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_convert_lat_lng_to_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metarstation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
