# Generated by Django 5.0.6 on 2024-05-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_metarstation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='metardata',
            name='conditions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metardata',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metardata',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
