# Generated by Django 5.0.6 on 2024-05-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_metardata_conditions_metardata_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metardata',
            name='conditions',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
