# Generated by Django 5.0.6 on 2024-06-04 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GFSParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('level', models.BigIntegerField()),
                ('type_of_level', models.CharField(max_length=255)),
                ('parameter_id', models.IntegerField(unique=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('parameter_id', 'level', 'type_of_level')},
            },
        ),
        migrations.CreateModel(
            name='GFSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_hours', models.CharField(default='24', max_length=255)),
                ('countries', models.ManyToManyField(related_name='gfs_configs', to='geography.geographiccountry')),
                ('parameters', models.ManyToManyField(blank=True, to='gfs_management.gfsparameter')),
            ],
        ),
    ]
