# Generated by Django 5.0.6 on 2024-05-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfs_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GFSForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_time', models.DateTimeField()),
                ('data', models.JSONField()),
            ],
        ),
    ]
