# Generated by Django 5.0.6 on 2024-06-08 07:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfs_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GFSForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('forecast_data', models.JSONField()),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('utc_cycle_time', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='GFSConfig',
        ),
    ]
