# Generated by Django 5.0.6 on 2024-05-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfs_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfsparameter',
            name='parameter_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
