# Generated by Django 5.0.6 on 2024-06-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfs_management', '0002_add_number_to_gfsparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfsparameter',
            name='number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
