# Generated by Django 5.0.6 on 2024-05-31 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfs_management', '0002_gfsforecast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GFSForecast',
        ),
    ]
