# Generated by Django 5.0.6 on 2024-05-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfs_management', '0002_gfsparameter_parameter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfsparameter',
            name='parameter_id',
            field=models.IntegerField(unique=True),
        ),
    ]
