# Generated by Django 5.0.6 on 2024-06-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfs_management', '0002_gfsforecast_delete_gfsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfsparameter',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
