# Generated by Django 5.0.6 on 2024-05-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfs_management', '0003_alter_gfsparameter_parameter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfsparameter',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='gfsparameter',
            unique_together={('parameter_id', 'level', 'type_of_level')},
        ),
    ]
