# Generated by Django 5.0.6 on 2024-05-28 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfs_management', '0004_alter_gfsparameter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfsparameter',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
